// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqPiYx4eDiJlXNkk-nvbb0kxAa51oD8ow',
    appId: '1:1046267206023:web:6854e8a6db8d9908b49b22',
    messagingSenderId: '1046267206023',
    projectId: 'buenavista-9b6df',
    authDomain: 'buenavista-9b6df.firebaseapp.com',
    storageBucket: 'buenavista-9b6df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY27DVHwB5xi4YL0RkBFZxePTzBi1ahLs',
    appId: '1:1046267206023:android:f518e9f0b7d1d19db49b22',
    messagingSenderId: '1046267206023',
    projectId: 'buenavista-9b6df',
    storageBucket: 'buenavista-9b6df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnnDDPhcOWi_jDxrViLlkVgY2VYuBHyQ8',
    appId: '1:1046267206023:ios:090364e891ae766eb49b22',
    messagingSenderId: '1046267206023',
    projectId: 'buenavista-9b6df',
    storageBucket: 'buenavista-9b6df.appspot.com',
    iosBundleId: 'com.example.buenavista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnnDDPhcOWi_jDxrViLlkVgY2VYuBHyQ8',
    appId: '1:1046267206023:ios:090364e891ae766eb49b22',
    messagingSenderId: '1046267206023',
    projectId: 'buenavista-9b6df',
    storageBucket: 'buenavista-9b6df.appspot.com',
    iosBundleId: 'com.example.buenavista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqPiYx4eDiJlXNkk-nvbb0kxAa51oD8ow',
    appId: '1:1046267206023:web:82cbcea5d7b8b306b49b22',
    messagingSenderId: '1046267206023',
    projectId: 'buenavista-9b6df',
    authDomain: 'buenavista-9b6df.firebaseapp.com',
    storageBucket: 'buenavista-9b6df.appspot.com',
  );
}
